<a href="https://colab.research.google.com/github/sina90alz/PyTorch-projects/blob/main/00_pytorch_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 print("Hello, we start learning PyTorch")

Hello, we start learning PyTorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
print("Hello, we start learning PyTorch under GPU")

Hello, we start learning PyTorch under GPU


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensor

In [ ]:
# scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[1]

tensor(7)

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
MATRIX2 = torch.tensor([[1,2,3],
                        [5,2,4],
                        [5,9,8]])
MATRIX2


tensor([[1, 2, 3],
        [5, 2, 4],
        [5, 9, 8]])

In [ ]:
MATRIX2.ndim

2

In [ ]:
MATRIX2.shape

torch.Size([3, 3])

In [ ]:
TENSOR2 = torch.tensor([[[2,3],
                         [2,9],
                         [6,9],
                         [7,1]]])
TENSOR2

tensor([[[2, 3],
         [2, 9],
         [6, 9],
         [7, 1]]])

In [ ]:
TENSOR2.ndim

3

In [ ]:
TENSOR2.shape

torch.Size([1, 4, 2])

In [ ]:
TENSOR3 = torch.tensor([[[1,2],
                         [2,9]],
                        [[4,6],
                         [5,9]]])
TENSOR3

tensor([[[1, 2],
         [2, 9]],

        [[4, 6],
         [5, 9]]])

In [ ]:
TENSOR3.ndim

3

In [ ]:
TENSOR3.shape

torch.Size([2, 2, 2])

## Random Tensor

### A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent data

In [ ]:
TENSOR_RD00 = torch.rand(1,3,3)
TENSOR_RD00

tensor([[[0.7602, 0.4778, 0.2750],
         [0.3052, 0.3062, 0.7919],
         [0.4638, 0.7101, 0.0303]]])

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (2,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###gets default type dtype

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 # creating tensors like
 ten_zeroes = torch.zeros_like(one_to_ten)
 ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note** Tensor data type is one of the 3 big errors in PyTorch and deep learning:
1. Tensor not right datatyoe
2. Tensor not right shape
3. Tensor not right devide

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None, # type of your device tensor on as CPU or CUDA
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors (tensor operations)

In [ ]:
# create a tensor and add a ten
tensor_add = torch.tensor([1,2,3])
tensor_add + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by ten
tensor_add * 10

tensor([10, 20, 30])

In [ ]:
tensor_add

tensor([1, 2, 3])

### Matric multipication

Two main ways of performing multipication in neural networks and deep learning

1. Element-wise multipication
2. Matrix multipication (dot product)

In [ ]:
 # Element wise multipicatopn

 print(tensor_add, "*", tensor_add)
 print(f"Equals:  {tensor_add * tensor_add}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [ ]:
# Dot ptoduct
tensor_add.matmul(tensor_add)

tensor(14)

In [ ]:
torch.matmul(torch.rand(4,3), torch.rand(3,2))

tensor([[0.6278, 0.4151],
        [0.5158, 0.2308],
        [0.5126, 0.2044],
        [0.2209, 0.1625]])

### To fix tensor shape issues, we can manupilate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
 # create a tensor
 x = torch.arange(1, 100, 10)
 x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the mean, max
torch.min(x), x.min(), x.max()

(tensor(0), tensor(0), tensor(90))

In [ ]:
 # Find the mean, attention to the input type for the mean function
 torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# Find the position in the tensor with argmin() -> return the index position of target tensor where the minimum value occures
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch Tensor and NumPy

NumPy is a scientific numerical computing library.

And PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.Numpy()`

In [ ]:
 # Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Attention to the type difference, numpy is by default 64, torch is 32
array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductubility (Trying to take random out of random)

How neural network learns

 `start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ...`

 To reduce randomness in neural networks and PyTorch comes the concept of **random seed**.
 Essentially what the random seed does is "flavour the randomness ."

In [ ]:
torch.rand(3,3)

tensor([[0.3725, 0.1349, 0.2062],
        [0.6546, 0.4532, 0.6179],
        [0.9232, 0.7733, 0.0067]])

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.8535, 0.0447, 0.4307, 0.4948],
        [0.9873, 0.8452, 0.6387, 0.5656],
        [0.7088, 0.6211, 0.2209, 0.4551]])
tensor([[0.1236, 0.6414, 0.9761, 0.9360],
        [0.6950, 0.8844, 0.3182, 0.9687],
        [0.2460, 0.1186, 0.8768, 0.6427]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make random but reproductible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU (Making faster computation)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA + PyTorch

### 1. Getting a GPU

1. Easiest - Use google colab for a free GPU
2. Use your own GPU - takes a bit of steps and requires investment
3. Use cloud computing -GCP, AWS, AZURE

for 2 and 3, PyTorch + GPU drivers (CUDA) takes a bit of setting up, refer to PyTorch setup documentations

### 2. Check for GPU access with PyTorch

In [ ]:
# Chack for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it is capable of running compute on GPU or CPU it's best practice to setup code :
https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [ ]:
# Count numbers of devices (usual if you have large models)
torch.cude.device_count()

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/Models on the GPU is because using a GPU result in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on a GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])